
version: 2

sources:
    - name: staging
      database: dtc-data-engineering-375007
      schema: trips_data_all

      tables:
        - name: green_taxi_data
        - name: yellow_taxi_data
        - name: fhv_taxi_data_local